name: A-SABR Benchmarks Comparaison

on:
  pull_request:
    branches: ["*"]

permissions:
  pull-requests: write

jobs:
  benchmark:
    name: Compare Bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2
      - uses: boa-dev/criterion-compare-action@v3
        with:
          branchName: ${{ github.base_ref }}
